# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a2c9d27528410b715183aa7452815594fdd20a85cd8effa29638d7707d54637696a6b7e6168d807d878ea5ed0ffe2a9c051c3e86ec1895afc397a43c6b1c251

test:
  secret_key_base: 65b281d17aac4330aaf77a25c9ff7b003e1944d0449eab820a9f2609978b902982120d26f18316ec2bdadbdf5e885eb13dcd670f13021744612b2c58f8760680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
